# Generated by Django 4.2.9 on 2025-12-25 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceavailability',
            name='provider',
            field=models.ForeignKey(limit_choices_to={'role': 'SERVICE_PROVIDER'}, on_delete=django.db.models.deletion.CASCADE, related_name='availability_schedule', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='provider',
            field=models.ForeignKey(limit_choices_to={'role': 'SERVICE_PROVIDER'}, on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.servicecategory'),
        ),
        migrations.AddField(
            model_name='service',
            name='provider',
            field=models.ForeignKey(limit_choices_to={'role': 'SERVICE_PROVIDER'}, on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='serviceimage',
            index=models.Index(fields=['service', 'order'], name='service_ima_service_7189df_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['is_active', 'order'], name='service_cat_is_acti_639f24_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['parent', 'is_active'], name='service_cat_parent__0cf16c_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceavailability',
            index=models.Index(fields=['provider', 'day_of_week', 'is_available'], name='service_ava_provide_e59032_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceavailability',
            unique_together={('provider', 'day_of_week', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='servicearea',
            index=models.Index(fields=['city', 'state', 'is_active'], name='service_are_city_11a798_idx'),
        ),
        migrations.AddIndex(
            model_name='servicearea',
            index=models.Index(fields=['provider', 'is_active'], name='service_are_provide_8ece89_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicearea',
            unique_together={('provider', 'city', 'state')},
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['provider', 'is_active'], name='services_provide_c85dc3_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', 'is_active'], name='services_categor_6a9f2f_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active', 'is_featured'], name='services_is_acti_f3b61c_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['-average_rating', '-review_count'], name='services_average_180239_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['-created_at'], name='services_created_6a9750_idx'),
        ),
    ]
