.PHONY: help install migrate createsuperuser run celery beat test clean docker-up docker-down

help:
	@echo "Available commands:"
	@echo "  make install          - Install dependencies"
	@echo "  make migrate          - Run database migrations"
	@echo "  make createsuperuser  - Create superuser"
	@echo "  make run              - Run development server"
	@echo "  make celery           - Run Celery worker"
	@echo "  make beat             - Run Celery beat"
	@echo "  make test             - Run tests"
	@echo "  make clean            - Clean Python cache files"
	@echo "  make docker-up        - Start Docker containers"
	@echo "  make docker-down      - Stop Docker containers"

install:
	pip install -r requirements.txt

migrate:
	python manage.py makemigrations
	python manage.py migrate

createsuperuser:
	python manage.py createsuperuser

run:
	python manage.py runserver

celery:
	celery -A config worker -l info

beat:
	celery -A config beat -l info

test:
	pytest

clean:
	find . -type d -name "__pycache__" -exec rm -rf {} +
	find . -type f -name "*.pyc" -delete
	find . -type f -name "*.pyo" -delete
	find . -type f -name ".coverage" -delete
	rm -rf htmlcov/
	rm -rf .pytest_cache/

docker-up:
	docker-compose up -d

docker-down:
	docker-compose down

docker-build:
	docker-compose up --build -d

docker-logs:
	docker-compose logs -f

shell:
	python manage.py shell

dbshell:
	python manage.py dbshell

collectstatic:
	python manage.py collectstatic --noinput